### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by punkpeye** [isaacwasserman/mcp-snowflake-server#2]
I'm trying to start this server so I can mark the associated [listing](https://glama.ai/mcp/servers/1z9lezliya) as tested.

### Current Behavior

This is my `Dockerfile`:

```Dockerfile
FROM python:3.10

RUN pip install uv

WORKDIR /app

RUN git clone https://github.com/isaacwasserman/mcp-snowflake-server .

RUN uv sync

CMD ["uv", "run", "mcp_snowflake_server"]
```

When I run it, I get the following error:

```
2024-12-25 14:58:21,064 - mcp_snowflake_server - INFO - Starting MCP Snowflake Server
2024-12-25 14:58:21,064 - mcp_snowflake_server - INFO - Starting Snowflake MCP Server
2024-12-25 14:58:21,065 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.10.16, Platform: Linux-6.12.5-orbstack-00287-gf8da5d508983-aarch64-with-glibc2.36
2024-12-25 14:58:21,065 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain
2024-12-25 14:58:21,065 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/snowflake/snowpark/session.py", line 491, in getOrCreate
    session = _get_active_session()
  File "/app/.venv/lib/python3.10/site-packages/snowflake/snowpark/session.py", line 284, in _get_active_session
    raise SnowparkClientExceptionMessages.SERVER_NO_DEFAULT_SESSION()
snowflake.snowpark.exceptions.SnowparkSessionException: (1403): No default Session is found. Please create a session before you call function 'udf' or use decorator '@udf'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/bin/mcp_snowflake_server", line 8, in <module>
    sys.exit(main())
  File "/app/src/mcp_snowflake_server/__init__.py", line 12, in main
    asyncio.run(server.main(allow_write=args.allow_write))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/src/mcp_snowflake_server/server.py", line 96, in main
    db = SnowflakeDB(connection_config)
  File "/app/src/mcp_snowflake_server/server.py", line 28, in __init__
    self._init_database()
  File "/app/src/mcp_snowflake_server/server.py", line 34, in _init_database
    self.session = Session.builder.configs(self.connection_config).getOrCreate()
  File "/app/.venv/lib/python3.10/site-packages/snowflake/snowpark/session.py", line 498, in getOrCreate
    return self.create()
  File "/app/.venv/lib/python3.10/site-packages/snowflake/snowpark/session.py", line 476, in create
    session = self._create_internal(self._options.get("connection"))
  File "/app/.venv/lib/python3.10/site-packages/snowflake/snowpark/session.py", line 518, in _create_internal
    ServerConnection({}, conn) if conn else ServerConnection(self._options),
  File "/app/.venv/lib/python3.10/site-packages/snowflake/snowpark/_internal/server_connection.py", line 164, in __init__
    self._conn = conn if conn else connect(**self._lower_case_parameters)
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 55, in Connect
    return SnowflakeConnection(**kwargs)
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 457, in __init__
    self.connect(**kwargs)
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 772, in connect
    self.__open_connection()
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1100, in __open_connection
    self.authenticate_with_retry(self.auth_class)
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1387, in authenticate_with_retry
    self._authenticate(auth_instance)
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1415, in _authenticate
    auth.authenticate(
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/auth/_auth.py", line 264, in authenticate
    ret = self._rest._post_request(
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 748, in _post_request
    ret = self.fetch(
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 863, in fetch
    ret = self._request_exec_wrapper(
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 991, in _request_exec_wrapper
    raise e
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 913, in _request_exec_wrapper
    return_object = self._request_exec(
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 1190, in _request_exec
    raise err
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 1139, in _request_exec
    raise_failed_request_error(
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 231, in raise_failed_request_error
    Error.errorhandler_wrapper(
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 342, in hand_to_other_handler
    connection.errorhandler(connection, cursor, error_class, error_value)
  File "/app/.venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.InterfaceError: 250003 (08001): None: 404 Not Found: post https://example_account_id.snowflakecomputing.com:443/session/v1/login-request?request_id=5b56ba86-c2b8-4538-b04a-b83ec8dd12ca&databaseName=example_database&schemaName=example_schema&warehouse=example_warehouse&roleName=example_role&request_guid=117d60aa-7cf3-41e0-818f-7e74166c7b47

```

### Expected Behavior

The server should start correctly when using `uv run`.

### Suggested Improvement

The issue here is that the server will not start without valid credentials. It seems it tries to connect to the snowflake server before starting MCP server. Ideally, connection would be delayed until actual tools are invoked.

This would improve usability for developers and help automated systems like [Glama](https://glama.ai/mcp/servers) to test the server

**Comment by isaacwasserman** [comment]
Thanks for pointing this out. The issue has been fixed in the latest release. Let me know if you find any new issues.
